# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'abc.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):

    def __init__(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 598)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 761, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.training = QtWidgets.QWidget()
        self.training.setObjectName("training")
        self.train_logs = QtWidgets.QScrollArea(self.training)
        self.train_logs.setGeometry(QtCore.QRect(10, 240, 731, 271))
        self.train_logs.setWidgetResizable(True)
        self.train_logs.setObjectName("train_logs")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 729, 269))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.train_logs.setWidget(self.scrollAreaWidgetContents)
        self.image = QtWidgets.QPushButton(self.training)
        self.image.setGeometry(QtCore.QRect(10, 10, 111, 41))
        self.image.setObjectName("image")
        self.mask = QtWidgets.QPushButton(self.training)
        self.mask.setGeometry(QtCore.QRect(140, 10, 101, 41))
        self.mask.setObjectName("mask")
        self.train_start = QtWidgets.QPushButton(self.training)
        self.train_start.setGeometry(QtCore.QRect(470, 50, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.train_start.setFont(font)
        self.train_start.setStyleSheet("background-color: rgb(154, 255, 39);")
        self.train_start.setObjectName("train_start")
        self.train_stop = QtWidgets.QPushButton(self.training)
        self.train_stop.setGeometry(QtCore.QRect(470, 120, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.train_stop.setFont(font)
        self.train_stop.setStyleSheet("background-color: rgb(200, 54, 9);")
        self.train_stop.setObjectName("train_stop")
        self.label = QtWidgets.QLabel(self.training)
        self.label.setGeometry(QtCore.QRect(20, 70, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.epoch = QtWidgets.QSpinBox(self.training)
        self.epoch.setGeometry(QtCore.QRect(160, 80, 71, 31))
        self.epoch.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.epoch.setMaximum(200)
        self.epoch.setProperty("value", 4)
        self.epoch.setObjectName("epoch")
        self.label_2 = QtWidgets.QLabel(self.training)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lr = QtWidgets.QDoubleSpinBox(self.training)
        self.lr.setGeometry(QtCore.QRect(150, 130, 81, 31))
        self.lr.setDecimals(4)
        self.lr.setSingleStep(0.0001)
        self.lr.setProperty("value", 0.0001)
        self.lr.setObjectName("lr")
        self.label_3 = QtWidgets.QLabel(self.training)
        self.label_3.setGeometry(QtCore.QRect(270, 180, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.training, "")
        self.evaluation = QtWidgets.QWidget()
        self.evaluation.setObjectName("evaluation")
        self.image_upload = QtWidgets.QPushButton(self.evaluation)
        self.image_upload.setGeometry(QtCore.QRect(50, 30, 161, 41))
        self.image_upload.setObjectName("image_upload")
        self.weight_upload = QtWidgets.QPushButton(self.evaluation)
        self.weight_upload.setGeometry(QtCore.QRect(260, 30, 161, 41))
        self.weight_upload.setObjectName("weight_upload")
        self.weight_params = QtWidgets.QLabel(self.evaluation)
        self.weight_params.setGeometry(QtCore.QRect(10, 90, 731, 111))
        self.weight_params.setObjectName("weight_params")
        self.input_img = QtWidgets.QLabel(self.evaluation)
        self.input_img.setGeometry(QtCore.QRect(10, 230, 371, 281))
        self.input_img.setText("")
        self.input_img.setPixmap(QtGui.QPixmap("C:/Users/Kamaljeet/Downloads/room.jpg"))
        self.input_img.setScaledContents(True)
        self.input_img.setObjectName("input_img")
        self.output_img = QtWidgets.QLabel(self.evaluation)
        self.output_img.setGeometry(QtCore.QRect(400, 230, 341, 281))
        self.output_img.setText("")
        self.output_img.setPixmap(QtGui.QPixmap("C:/Users/Kamaljeet/Downloads/room1.jpg"))
        self.output_img.setScaledContents(True)
        self.output_img.setWordWrap(False)
        self.output_img.setObjectName("output_img")
        self.tabWidget.addTab(self.evaluation, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.image.setText(_translate("MainWindow", "Image Directory"))
        self.mask.setText(_translate("MainWindow", "Mask Directory"))
        self.train_start.setText(_translate("MainWindow", "Start Train"))
        self.train_stop.setText(_translate("MainWindow", "Stop Train"))
        self.label.setText(_translate("MainWindow", "Epochs"))
        self.label_2.setText(_translate("MainWindow", "Learning Rate"))
        self.label_3.setText(_translate("MainWindow", "Training Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.training), _translate("MainWindow", "Tab 1"))
        self.image_upload.setText(_translate("MainWindow", "Upload Image"))
        self.weight_upload.setText(_translate("MainWindow", "Upload Weight"))
        self.weight_params.setText(_translate("MainWindow", "Weight_Params"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.evaluation), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(MainWindow)
    #ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
